-- Basisschema (Struktur). Policies und Rechte stehen in 0002_security.sql.
-- Ohne 0002 ist keine Rolle ausser service_role zugriffsberechtigt.


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."get_last_tour_per_driver"() RETURNS TABLE("driver_id" integer, "last_tour" "date")
    LANGUAGE "sql"
    SET "search_path" TO 'public'
    AS $$
select fahrer_id as driver_id, max(datum) as last_tour
from (select "fahrerA_id" as fahrer_id, datum
      from fahrten
      union all
      select "fahrerB_id" as fahrer_id, datum
      from fahrten) combined
where fahrer_id is not null
group by fahrer_id
    $$;


ALTER FUNCTION "public"."get_last_tour_per_driver"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_letzte_fahrten_pro_fahrer"() RETURNS TABLE("fahrer_id" integer, "letzte_fahrt" "date")
    LANGUAGE "sql"
    SET "search_path" TO 'public'
    AS $$
  select fahrer_id, max(datum) as letzte_fahrt
  from (
    select "fahrerA_id" as fahrer_id, datum from fahrten
    union all
    select "fahrerB_id" as fahrer_id, datum from fahrten
  ) combined
  where fahrer_id is not null
  group by fahrer_id
$$;


ALTER FUNCTION "public"."get_letzte_fahrten_pro_fahrer"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_unique_attendance_ids"() RETURNS TABLE("anwesend_ids" "jsonb")
    LANGUAGE "sql"
    SET "search_path" TO 'public'
    AS $$
  WITH alle_ids AS (
    SELECT
      f.id AS fahrt_id,
      (jsonb_array_elements_text(f.anwesend_ids)::int) AS id
    FROM fahrten f
  ),
  gefiltert AS (
    SELECT fahrt_id, id
    FROM alle_ids
    WHERE id NOT IN (SELECT id FROM fahrer WHERE startpunkt = 2)
  ),
  gruppiert AS (
    SELECT fahrt_id, jsonb_agg(id ORDER BY id) AS ids
    FROM gefiltert
    GROUP BY fahrt_id
  )
SELECT DISTINCT ids AS anwesend_ids FROM gruppiert;
$$;


ALTER FUNCTION "public"."get_unique_attendance_ids"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_unique_zw_attendance_ids"() RETURNS TABLE("anwesend_ids" "jsonb")
    LANGUAGE "sql"
    SET "search_path" TO 'public'
    AS $$
  WITH alle_ids AS (
    SELECT
      f.id AS fahrt_id,
      (jsonb_array_elements_text(f.anwesend_ids)::int) AS id
    FROM fahrten f
  ),
  gefiltert AS (
    SELECT fahrt_id, id
    FROM alle_ids
    WHERE id NOT IN (SELECT id FROM fahrer WHERE startpunkt = 1)
  ),
  gruppiert AS (
    SELECT fahrt_id, jsonb_agg(id ORDER BY id) AS ids
    FROM gefiltert
    GROUP BY fahrt_id
  )
  SELECT DISTINCT ids AS anwesend_ids FROM gruppiert;
$$;


ALTER FUNCTION "public"."get_unique_zw_attendance_ids"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."load_tours"() RETURNS TABLE("id" integer, "datum" "date", "fahrera_id" integer, "fahrerb_id" integer, "anwesend_ids" "jsonb", "max_datum" "date")
    LANGUAGE "sql"
    SET "search_path" TO 'public'
    AS $$
  SELECT
    f.id,
    f.datum,
    f."fahrerA_id",
    f."fahrerB_id",
    f."anwesend_ids",
    (SELECT MAX(datum) FROM fahrten) AS max_datum
  FROM fahrten f
  ORDER BY datum ASC
$$;


ALTER FUNCTION "public"."load_tours"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."fahrer" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "startpunkt" smallint,
    "label" "text"
);


ALTER TABLE "public"."fahrer" OWNER TO "postgres";


ALTER TABLE "public"."fahrer" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fahrer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fahrten" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "datum" "date",
    "id" bigint NOT NULL,
    "anwesend_ids" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "fahrerA_id" bigint,
    "fahrerB_id" bigint
);


ALTER TABLE "public"."fahrten" OWNER TO "postgres";


ALTER TABLE "public"."fahrten" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fahrten_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."invites" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "code" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "used" boolean DEFAULT false,
    "used_by" "text",
    "email" "text",
    "role" "text" DEFAULT 'user'::"text",
    "expires_at" timestamp without time zone
);


ALTER TABLE "public"."invites" OWNER TO "postgres";


ALTER TABLE ONLY "public"."fahrer"
    ADD CONSTRAINT "fahrer_label_key" UNIQUE ("label");



ALTER TABLE ONLY "public"."fahrer"
    ADD CONSTRAINT "fahrer_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."fahrer"
    ADD CONSTRAINT "fahrer_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."invites"
    ADD CONSTRAINT "invites_code_key" UNIQUE ("code");



ALTER TABLE ONLY "public"."invites"
    ADD CONSTRAINT "invites_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fahrten"
    ADD CONSTRAINT "fahrten_fahrerA_id_fkey" FOREIGN KEY ("fahrerA_id") REFERENCES "public"."fahrer"("id") ON UPDATE CASCADE ON DELETE SET DEFAULT;



ALTER TABLE ONLY "public"."fahrten"
    ADD CONSTRAINT "fahrten_fahrerB_id_fkey" FOREIGN KEY ("fahrerB_id") REFERENCES "public"."fahrer"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE "public"."fahrer" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fahrten" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invites" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."get_last_tour_per_driver"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_last_tour_per_driver"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_letzte_fahrten_pro_fahrer"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_letzte_fahrten_pro_fahrer"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_unique_attendance_ids"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_unique_attendance_ids"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_unique_zw_attendance_ids"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_unique_zw_attendance_ids"() TO "service_role";



GRANT ALL ON FUNCTION "public"."load_tours"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."load_tours"() TO "service_role";



GRANT ALL ON TABLE "public"."fahrer" TO "authenticated";
GRANT ALL ON TABLE "public"."fahrer" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fahrer_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fahrer_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fahrten" TO "authenticated";
GRANT ALL ON TABLE "public"."fahrten" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fahrten_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fahrten_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."invites" TO "authenticated";
GRANT ALL ON TABLE "public"."invites" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






